// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyTravel.Infrastructure;

namespace SkyTravel.Infrastructure.Migrations
{
    [DbContext(typeof(SkyTravelDbContext))]
    [Migration("20210210054828_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("SkyTravel.Core.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvalaibleDates")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LuxuryQuality")
                        .HasColumnType("TEXT");

                    b.Property<string>("NearByActivities")
                        .HasColumnType("TEXT");

                    b.Property<float>("PriceByNight")
                        .HasColumnType("REAL");

                    b.Property<string>("TypeofBuilding")
                        .HasColumnType("TEXT");

                    b.Property<string>("WiFiQuality")
                        .HasColumnType("TEXT");

                    b.Property<bool>("state")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Destionations");
                });
#pragma warning restore 612, 618
        }
    }
}
